### ISSUE TITLE
cannot use natives- classifier prefix

### ISSUE THREAD

**Issue by adrian-herscu** [fmarot/nativedependencies-maven#28]
There are JAR artifacts which bundle native libraries for all supported platforms, for example `netty-tcnative-boringssl-static`.

This one does not have a classifier at all. Moreover, its platform-specific variants have classifiers such as: `windows-x86_64`, `linux`, etc. Hence the current plugin does not process these at all, since it expects native artifacts to have classifiers prefixed with `native-`.

Please make the expected classifier a parameter.

**Comment by fmarot** [comment]
Hi and thanks for creating the issue.
I have had a look by myself at netty and here is what I think (I may, have missed something, so please tell me in any case):
- added the following dependency to a project
```
<dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-tcnative-boringssl-static</artifactId>
      <version>1.1.33.Fork16</version>
      <classifier>linux-x86_64</classifier>
</dependency>
```
Then I realized that the jar I got from it was a real java jar containing a .so file in META-INF/native/. So I think that the .so native library is automatically extracted at runtime by whatever tool netty uses (is it HawtJNI ?).
So in the end, I *think* that you do not need the nativedependencies-maven-plugin because there is no need to unpack the jar.
Usually, jars or zip handled by nativedependencies-maven-plugin will contain only a bunch of .dll or .so files.

Am I mistaken ?

**Comment by adrian-herscu** [comment]
Yes, you are right. Netty manages the extraction itself.

**Comment by fmarot** [comment]
closing because no issue
